[versions]
androidGradlePlugin = "7.3.1"
androidxActivity = "1.6.1"
androidxCoreKtx = "1.9.0"
androidxCompose = "1.3.1"
androidxComposeCompiler = "1.3.2"
androidxEspresso = "3.5.0"
androidxLifecycle = "2.5.1"
androidxTestExt = "1.1.4"
detekt = "1.21.0"
detektComposeRules = "0.0.24"
junit4 = "4.13.2"
kotlin = "1.7.20"
kover = "0.6.1"
ktlint = "0.45.2"
material3 = "1.0.1"
spotless = "6.11.0"

#androidx.compose.ui:ui-tooling

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidxCompose" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidxCompose" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidxCompose" }
androidx-compose-ui-tooling= { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidxCompose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidxCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
detekt-compose-rules = { group = "com.twitter.compose.rules", name = "detekt", version.ref = "detektComposeRules"}
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
detekt-plugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kover-plugin = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
spotless-plugin = { id = "com.diffplug.spotless", version.ref = "spotless" }
